#!/usr/bin/env bash
set -Eeuo pipefail

# frp-manager-lite one-click production deployer.
# Installs/updates Docker Compose panel + host frps systemd service.
# Designed for Debian/Ubuntu root servers. Run from the project checkout:
#   sudo bash scripts/deploy-production.sh
# Non-interactive example:
#   PANEL_DOMAIN=panel.example.com FRPS_DOMAIN=frp.example.com \
#   FML_ADMIN_PASSWORD='...' FRP_AUTH_TOKEN='...' \
#   bash scripts/deploy-production.sh

APP_NAME="frp-manager-lite"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

FRP_VERSION="${FRP_VERSION:-0.62.1}"
FML_PUBLISH_PORT="${FML_PUBLISH_PORT:-18081}"
FML_ADMIN_USER="${FML_ADMIN_USER:-admin}"
FRPS_BIND_PORT="${FRPS_BIND_PORT:-7000}"
FRPS_PORT_START="${FRPS_PORT_START:-20000}"
FRPS_PORT_END="${FRPS_PORT_END:-20199}"
FRPS_WEB_PORT="${FRPS_WEB_PORT:-7500}"
INSTALL_NGINX="${INSTALL_NGINX:-auto}"      # auto|0|1
ENABLE_HTTPS="${ENABLE_HTTPS:-auto}"        # auto|0|1; requires PANEL_DOMAIN
ENABLE_UFW="${ENABLE_UFW:-0}"                # 0 by default to avoid locking out SSH
PANEL_DOMAIN="${PANEL_DOMAIN:-}"
FRPS_DOMAIN="${FRPS_DOMAIN:-}"
PANEL_PLUGIN_ADDR="${PANEL_PLUGIN_ADDR:-127.0.0.1:${FML_PUBLISH_PORT}}"

log() { printf '\033[1;34m[deploy]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; }
need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    err "Please run as root, e.g. sudo bash scripts/deploy-production.sh"
    exit 1
  fi
}

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d '\n'
  else
    tr -dc 'A-Za-z0-9_=-' </dev/urandom | head -c 43
  fi
}

prompt_value() {
  local var_name="$1" prompt="$2" default_value="${3:-}"
  local current="${!var_name:-}"
  if [[ -n "${current}" ]]; then
    return 0
  fi
  if [[ ! -t 0 ]]; then
    printf -v "${var_name}" '%s' "${default_value}"
    return 0
  fi
  local input
  if [[ -n "${default_value}" ]]; then
    read -r -p "${prompt} [${default_value}]: " input
    printf -v "${var_name}" '%s' "${input:-${default_value}}"
  else
    read -r -p "${prompt}: " input
    printf -v "${var_name}" '%s' "${input}"
  fi
}

prompt_secret() {
  local var_name="$1" prompt="$2"
  local current="${!var_name:-}"
  if [[ -n "${current}" ]]; then
    return 0
  fi
  local generated
  generated="$(random_secret)"
  if [[ ! -t 0 ]]; then
    printf -v "${var_name}" '%s' "${generated}"
    return 0
  fi
  local input
  read -r -s -p "${prompt} [Enter 自动生成]: " input
  printf '\n'
  printf -v "${var_name}" '%s' "${input:-${generated}}"
}

require_supported_os() {
  if [[ -r /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    case "${ID:-}" in
      debian|ubuntu) return 0 ;;
    esac
  fi
  warn "This script is tested on Debian/Ubuntu. Continuing anyway."
}

apt_install_base() {
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y ca-certificates curl tar gzip openssl lsb-release
}

install_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    log "Docker Compose already installed: $(docker compose version --short 2>/dev/null || docker compose version)"
    return 0
  fi
  log "Installing Docker Engine and Compose plugin"
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
  docker compose version
}

write_env_file() {
  local env_file="${PROJECT_DIR}/.env"
  if [[ -f "${env_file}" ]]; then
    local backup="${env_file}.bak.$(date +%Y%m%d-%H%M%S)"
    cp -a "${env_file}" "${backup}"
    log "Backed up existing .env to ${backup}"
  fi

  cat > "${env_file}" <<ENV
# Generated by scripts/deploy-production.sh at $(date -Is)
FML_PUBLISH_PORT=${FML_PUBLISH_PORT}
FML_ADMIN_USER=${FML_ADMIN_USER}
FML_ADMIN_PASSWORD=${FML_ADMIN_PASSWORD}
FML_PORT_START=${FRPS_PORT_START}
FML_PORT_END=${FRPS_PORT_END}
FML_DEFAULT_MAX_PORTS=${FML_DEFAULT_MAX_PORTS:-5}

FRP_SERVER_ADDR=${FRPS_DOMAIN}
FRP_SERVER_PORT=${FRPS_BIND_PORT}
FRP_AUTH_TOKEN=${FRP_AUTH_TOKEN}
ENV
  chmod 600 "${env_file}"
  log "Wrote ${env_file}"
}

start_panel() {
  log "Building and starting ${APP_NAME} panel"
  (cd "${PROJECT_DIR}" && docker compose up -d --build)
  log "Waiting for panel health endpoint"
  for _ in $(seq 1 30); do
    if curl -fsS "http://127.0.0.1:${FML_PUBLISH_PORT}/api/nodes" >/dev/null 2>&1; then
      log "Panel is reachable at http://127.0.0.1:${FML_PUBLISH_PORT}"
      return 0
    fi
    sleep 2
  done
  warn "Panel did not become ready within 60s. Check: cd ${PROJECT_DIR} && docker compose logs --tail=100"
}

frp_arch() {
  local machine
  machine="$(uname -m)"
  case "${machine}" in
    x86_64|amd64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    armv7l|armv7*) echo "arm" ;;
    i386|i686) echo "386" ;;
    *) err "Unsupported CPU architecture: ${machine}"; exit 1 ;;
  esac
}

install_frps_binary() {
  local arch package url tmpdir
  arch="$(frp_arch)"
  package="frp_${FRP_VERSION}_linux_${arch}"
  url="https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/${package}.tar.gz"
  tmpdir="$(mktemp -d)"

  if command -v frps >/dev/null 2>&1 && frps --version 2>/dev/null | grep -qx "${FRP_VERSION}"; then
    log "frps ${FRP_VERSION} already installed"
    rm -rf "${tmpdir}"
    return 0
  fi

  log "Downloading frps ${FRP_VERSION} (${arch})"
  curl -fL "${url}" -o "${tmpdir}/frp.tar.gz"
  tar -xzf "${tmpdir}/frp.tar.gz" -C "${tmpdir}"
  install -m 0755 "${tmpdir}/${package}/frps" /usr/local/bin/frps
  rm -rf "${tmpdir}"
  log "Installed $(/usr/local/bin/frps --version 2>/dev/null | sed 's/^/frps /')"
}

write_frps_config() {
  mkdir -p /etc/frp
  if [[ -f /etc/frp/frps.toml ]]; then
    cp -a /etc/frp/frps.toml "/etc/frp/frps.toml.bak.$(date +%Y%m%d-%H%M%S)"
    log "Backed up existing /etc/frp/frps.toml"
  fi

  cat > /etc/frp/frps.toml <<TOML
# Generated by frp-manager-lite scripts/deploy-production.sh at $(date -Is)
bindPort = ${FRPS_BIND_PORT}

auth.method = "token"
auth.token = "${FRP_AUTH_TOKEN}"

allowPorts = [
  { start = ${FRPS_PORT_START}, end = ${FRPS_PORT_END} }
]

webServer.addr = "127.0.0.1"
webServer.port = ${FRPS_WEB_PORT}
webServer.user = "admin"
webServer.password = "${FRPS_WEB_PASSWORD}"

# frp-manager-lite production authorization plugin.
# It validates user status, panelToken, licenseKey, machineId, proxy type, and port ownership.
[[httpPlugins]]
name = "frp-manager-lite-auth"
addr = "${PANEL_PLUGIN_ADDR}"
path = "/frp-plugin"
ops = ["Login", "NewProxy"]
TOML
  chmod 600 /etc/frp/frps.toml
  log "Wrote /etc/frp/frps.toml"
}

install_frps_service() {
  cat > /etc/systemd/system/frps.service <<'SERVICE'
[Unit]
Description=frp server
Documentation=https://github.com/fatedier/frp
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/frps -c /etc/frp/frps.toml
Restart=always
RestartSec=5
LimitNOFILE=1048576
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
SERVICE
  systemctl daemon-reload
  systemctl enable --now frps
  systemctl restart frps
  log "frps service status: $(systemctl is-active frps)"
}

install_nginx_if_requested() {
  local do_nginx="${INSTALL_NGINX}"
  if [[ "${do_nginx}" == "auto" ]]; then
    if [[ -n "${PANEL_DOMAIN}" ]]; then do_nginx="1"; else do_nginx="0"; fi
  fi
  [[ "${do_nginx}" == "1" ]] || return 0
  if [[ -z "${PANEL_DOMAIN}" ]]; then
    warn "INSTALL_NGINX=1 but PANEL_DOMAIN is empty; skipping Nginx."
    return 0
  fi

  export DEBIAN_FRONTEND=noninteractive
  apt-get install -y nginx
  cat > /etc/nginx/sites-available/frp-manager-lite <<NGINX
server {
    listen 80;
    server_name ${PANEL_DOMAIN};

    client_max_body_size 100m;

    location / {
        proxy_pass http://127.0.0.1:${FML_PUBLISH_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX
  ln -sfn /etc/nginx/sites-available/frp-manager-lite /etc/nginx/sites-enabled/frp-manager-lite
  nginx -t
  systemctl enable --now nginx
  systemctl reload nginx
  log "Nginx reverse proxy configured for ${PANEL_DOMAIN}"

  local do_https="${ENABLE_HTTPS}"
  if [[ "${do_https}" == "auto" ]]; then do_https="1"; fi
  if [[ "${do_https}" == "1" ]]; then
    apt-get install -y certbot python3-certbot-nginx
    log "Requesting Let's Encrypt certificate for ${PANEL_DOMAIN}"
    certbot --nginx -d "${PANEL_DOMAIN}" --non-interactive --agree-tos -m "admin@${PANEL_DOMAIN}" --redirect || \
      warn "Certbot failed. Check DNS points ${PANEL_DOMAIN} to this server, then run: certbot --nginx -d ${PANEL_DOMAIN}"
  fi
}

configure_ufw_if_requested() {
  [[ "${ENABLE_UFW}" == "1" ]] || return 0
  export DEBIAN_FRONTEND=noninteractive
  apt-get install -y ufw
  ufw allow OpenSSH || true
  ufw allow 80/tcp
  ufw allow 443/tcp
  ufw allow "${FRPS_BIND_PORT}/tcp"
  ufw allow "${FRPS_PORT_START}:${FRPS_PORT_END}/tcp"
  ufw allow "${FRPS_PORT_START}:${FRPS_PORT_END}/udp"
  ufw --force enable
  ufw status verbose
}

print_summary() {
  cat <<SUMMARY

Deployment complete.

Panel:
  Local:  http://127.0.0.1:${FML_PUBLISH_PORT}
  Public: ${PANEL_DOMAIN:+https://${PANEL_DOMAIN}}
  Admin:  ${FML_ADMIN_USER}

frps:
  Config: /etc/frp/frps.toml
  Bind:   ${FRPS_DOMAIN}:${FRPS_BIND_PORT}
  Ports:  ${FRPS_PORT_START}-${FRPS_PORT_END} tcp/udp
  Web UI: http://127.0.0.1:${FRPS_WEB_PORT}

Useful commands:
  cd ${PROJECT_DIR} && docker compose ps
  cd ${PROJECT_DIR} && docker compose logs -f
  systemctl status frps
  journalctl -u frps -f

Firewall/security group should allow:
  ${FRPS_BIND_PORT}/tcp
  ${FRPS_PORT_START}-${FRPS_PORT_END}/tcp
  ${FRPS_PORT_START}-${FRPS_PORT_END}/udp
  80/tcp and 443/tcp if using Nginx/HTTPS

In the panel admin node settings, use:
  frps address: ${FRPS_DOMAIN}
  bindPort:     ${FRPS_BIND_PORT}
  token:        the same FRP_AUTH_TOKEN written to .env and /etc/frp/frps.toml
  port range:   ${FRPS_PORT_START}-${FRPS_PORT_END}
SUMMARY
}

main() {
  need_root
  require_supported_os
  cd "${PROJECT_DIR}"

  prompt_value PANEL_DOMAIN "Panel domain, empty to skip Nginx/HTTPS" "${PANEL_DOMAIN}"
  local detected_frps_domain="${FRPS_DOMAIN}"
  if [[ -z "${detected_frps_domain}" ]]; then
    detected_frps_domain="${PANEL_DOMAIN:-$(hostname -f 2>/dev/null || hostname)}"
  fi
  prompt_value FRPS_DOMAIN "frps public domain/IP for frpc users" "${detected_frps_domain}"
  prompt_secret FML_ADMIN_PASSWORD "Panel admin password"
  prompt_secret FRP_AUTH_TOKEN "frps token"
  prompt_secret FRPS_WEB_PASSWORD "frps dashboard password"

  apt_install_base
  install_docker
  write_env_file
  start_panel
  install_frps_binary
  write_frps_config
  install_frps_service
  install_nginx_if_requested
  configure_ufw_if_requested
  print_summary
}

main "$@"
